export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CHANGE_STATE = "CHANGE_STATE";
export const DONE_TASK_FILTER = "DONE_TASK_FILTER";
export const NOT_DONE_TASK_FILTER = "NOT_DONE_TASK_FILTER";
export const ALL_TASK_FILTER = "ALL_TASK_FILTER";
export const DELETE_ALL_TASKS = "DELETE_ALL_TASKS";
